// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE9MYf1FO4_7MGXDz1K-6UhgdEu0cqdbA',
    appId: '1:686161977124:web:e40b0729b04948f10b5db1',
    messagingSenderId: '686161977124',
    projectId: 'expense-splitter-5e4a1',
    authDomain: 'expense-splitter-5e4a1.firebaseapp.com',
    storageBucket: 'expense-splitter-5e4a1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRMnpnlGEGqMC0t2SpYOFXmAUD0qJhC0Q',
    appId: '1:686161977124:android:b35a328036c9cd230b5db1',
    messagingSenderId: '686161977124',
    projectId: 'expense-splitter-5e4a1',
    storageBucket: 'expense-splitter-5e4a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHLV8VIqv_tdKKISm3C5el0PKY4dEsTQU',
    appId: '1:686161977124:ios:ed96648a7d27e3cc0b5db1',
    messagingSenderId: '686161977124',
    projectId: 'expense-splitter-5e4a1',
    storageBucket: 'expense-splitter-5e4a1.firebasestorage.app',
    iosBundleId: 'com.example.untitled5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHLV8VIqv_tdKKISm3C5el0PKY4dEsTQU',
    appId: '1:686161977124:ios:ed96648a7d27e3cc0b5db1',
    messagingSenderId: '686161977124',
    projectId: 'expense-splitter-5e4a1',
    storageBucket: 'expense-splitter-5e4a1.firebasestorage.app',
    iosBundleId: 'com.example.untitled5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE9MYf1FO4_7MGXDz1K-6UhgdEu0cqdbA',
    appId: '1:686161977124:web:127c6d104f2d944b0b5db1',
    messagingSenderId: '686161977124',
    projectId: 'expense-splitter-5e4a1',
    authDomain: 'expense-splitter-5e4a1.firebaseapp.com',
    storageBucket: 'expense-splitter-5e4a1.firebasestorage.app',
  );
}
